MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: 'output/weight/resnet50-19c8e357.pth'
  PRETRAIN_NAME: 'resnet50-19c8e357.pth'

  LAST_STRIDE: 1
  NECK: 'no'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'one'
  IF_WITH_CENTER: 'no'


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  # SIZE_TRAIN: [2, 4]
  # SIZE_TEST: [2, 4] # debug only

  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: 'aic'
  ROOT_DIR: /mnt/Data/dataset/ReiD/
  # ROOT_DIR: /mnt/ssd8tb/quang/
DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035
  # BASE_LR: 0.1
  MOMENTUM: 0.9
  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 0
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 20
  EVAL_PERIOD: 20
  SEED: 507
TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: "path"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "./ouptut"
CHECKPOINT_PATH: ""

