DATASETS:
  ROOT_DIR: /kaggle/input/person-reid/person_reid
  TRAIN_FILE: 'datasets/reid/train_set_reid.txt'
  GALLERY: 'datasets/reid/gallery_set_reid.txt'
  QUERY: 'datasets/reid/query_set_reid.txt'